### ISSUE TITLE
After update to v3.0.0, debug flag is on but has no effect until toggled

### ISSUE THREAD

**Issue by deitmerit** [fdegier/homebridge-jablotron-alarm#102]
**Describe The Problem:**
After updating to V3.0.0, I wanted to enable debug mode to get section IDs printed to the log. In the advanced settings, debug mode was displayed as on, but no ids were printed to the log. After switching debug mode off, restarting home bridge, then re-enabling debug mode and restarting homebridge again, section IDs were printed.

**To Reproduce:**
see above

**Logs:**
These are the only lines referencing jablotron in the log after updating to v3.0.0 and debug mode seemingly being enabled:

```
[11/19/2023, 2:39:45 PM] Loaded plugin: homebridge-jablotron@3.0.0
[11/19/2023, 2:39:45 PM] Registering platform 'homebridge-jablotron.Jablotron'
[11/19/2023, 2:39:45 PM] [Jablotron] Initializing Jablotron platform...
[11/19/2023, 2:39:45 PM] [Jablotron] Starting Jablotron platform...
[11/19/2023, 2:39:45 PM] [Jablotron] Initialising Jablotron service 156988
```

**Environment:**

* **Homebridge Version:** 1.7.0
* **Node Version:** 20.9.0
* **Homebridge-jablotron plugin version:** v3.0.0
* **Operating System and OS Version:** Docker

**Comment by deitmerit** [comment]
To be clear, after disabling debug mode and re-enabling, the ids where printed to the log and I could complete the transition to v3.0.0, so everything is working fine for me now.

**Comment by fdegier** [comment]
Did you restart homebridge after changing the config?
