### ISSUE TITLE
Thermometers not working in v3.0

### ISSUE THREAD

**Issue by Barney241** [fdegier/homebridge-jablotron-alarm#103]
**Describe The Problem:**
after upgrade to v3 the temperature of thermometers is not updated and always stays at 0.
i tried both of these properties as `segment_id` without any luck
```
"object-device-id": "THM-566680121",
"cloud-entity-id": "COMPONENT_<OBJECT_JA100F:3316669>:40",
```
even tried the old naming `THERMOMETER_40`

**Logs:**
states logs
```
{
      "object-device-id": "THM-566680121",
      "temperature": 49.9,
      "last-temperature-time": "2024-02-03T12:22:14+0100"
}
```
thermo logs
```
{
      "object-device-id": "THM-566680121",
      "cloud-entity-id": "COMPONENT_<OBJECT_JA100F:3316669>:40",
      "name": "xxx",
      "can-control": false,
      "can-show-graph": true,
      "unit": "°C",
      "type": "THERMOMETER"
 }
```

**Environment:**

* **Homebridge Version:** 1.7.0
* **Node Version:** v18.19.0
* **Homebridge-jablotron plugin version:** v3.0.0
* **Operating System and OS Version:** Ubuntu Jammy Jellyfish (22.04.3 LTS)

**Comment by fdegier** [comment]
Thanks for reporting, unfortunately I do not have any thermometers to test. Would you be willing to add me to your Jablotron account to test it? Otherwise we'll need to wait for someone else to add it.

**Comment by Barney241** [comment]
wouldnt it be enough if i sent you the new response of jablotron?

**Comment by fdegier** [comment]
We can give that a try but since I do not have any thermometers in my setup it's pretty difficult to test. Are you comfortable with NodeJS? You can easily run the plugin in local development mode and add the functionality if you have access to the thermometers.

**Comment by misncz** [comment]
@fdegier I plan to test thermometers and fix whatever issues I find. Unfortunstely I was busy with ither things and couldn’t have a look earlier when you finished  upgrade

@Barney241 I’m going to test it and fix if needed

**Comment by fdegier** [comment]
> @fdegier I plan to test thermometers and fix whatever issues I find. Unfortunstely I was busy with ither things and couldn’t have a look earlier when you finished  upgrade
> 
> 
> 
> @Barney241 I’m going to test it and fix if needed

Thanks @misncz for adding the thermometers. 

Are there any other bugs? I'm not aware of them other than the default Jablotron shenanigans

**Comment by Barney241** [comment]
> @fdegier I plan to test thermometers and fix whatever issues I find. Unfortunstely I was busy with ither things and couldn’t have a look earlier when you finished  upgrade
> 
> 
> 
> @Barney241 I’m going to test it and fix if needed

Thanks

**Comment by weizenmanncom** [comment]
Hi guys, I have the same issue.

I'm not very familiar with coding, but I could provide you access to 2 thermostats. Please let me know if I can contribute here.

**Comment by misncz** [comment]
@weizenmanncom @Barney241 Fix for broken thermometer functionality is on its way once @fdegier approves pull request
