### ISSUE TITLE
Support triggered alarm

### ISSUE THREAD

**Issue by fdegier** [fdegier/homebridge-jablotron-alarm#40]
Homekit supports a triggered alarm (state 4), Jablotron represents this in the API with the following response:

```json
{
    "data":
    {
        "service_data": [
        {
            "service_type": "oasis",
            "service_id": 123456,
            "data_status": "updated",
            "checksum": "c2bcaf44db369aa14238c6f7d992bd19",
            "service_events_type": "alarm",
            "service_events": [
                [1578052916, "Alarm - Section Obyvak"]
            ],
```

Normally the `service_events` is just an empty list, signaling its not triggered. 

Given that we now know this, we should be able to implement this.

A few concerns / unknowns:
- The service events are for the entire service.
- It gives an epoch and a string, the string has the section name.
- Does each segment has a service event as well? Or does it reflect in the segment_state?

Given that we fetch the status every minute we can just check if the alarm is triggered.

**Comment by fdegier** [comment]
@grzegorz914 do you think it would be valuable to implement this? I have a few concerns written above, therefor I haven't proceeded with this issue.

**Comment by grzegorz914** [comment]
This would be very helpful to represent triggered alarm and send notification if happening. 
Its no matter for me on which section this happen, in main functionality we know the alarm was triggered
