### ISSUE TITLE
help to configure

### ISSUE THREAD

**Issue by SilvioMigu** [fdegier/homebridge-jablotron-alarm#63]
Goodnight
I have the jablotron 100 alarm at home, and I have hoobs installed, working with other plugins like shelly and others...
However, I don't know anything about programming, but I like to use Homekit.

"MAKE SURE YOU HAVE ACCEPTED THE JABLOTRON TERMS OF SERVICE OR YOUR ACCOUNT WILL NOT WORK."
In my jablotron app or on pc, after having installed the plugin, it didn't appear anywhere for me to accept the terms?
What did I do wrong ?

So I installed the Jablotron plugin, and copied the configuration and changed only the following parameters:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-155"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "Jablotron",
            "name": "Jablotron",
            "services": [
                {
                    "id": 123456,                            I don't know, where will I see the ID???
                    "name": "Home",
                    "username": "username",       I entered my email
                    "password": "password",        I entered my password
                    "pincode": "pincode",              I entered my code
                    "autoRefresh": true,
                    "pollInterval": 60,
                    "refreshOnStateChange": true,
                    "debug": false,
                    "sections": [
                        {
                            "name": "House",
                            "segment_id": "STATE_1",
                            "segment_key": "section_1",
                            "keyboard_key": "keyboard_2_3",
                            "partiallyArmedMode": "Night"
                        },
                        {
                            "name": "Cell",
                            "segment_id": "STATE_2",
                            "segment_key": "section_2",
                            "armedMode": "Home"
                        },
                        {
                            "name": "Terrace",
                            "segment_id": "STATE_3",
                            "segment_key": "section_3"
                        }
                    ],
                    "switches": [
                        {
                            "name": "Hooter",
                            "segment_id": "PGM_1",
                            "segment_key": "pgm_1"
                        }
                    ],
                    "outlets": [
                        {
                            "name": "Camera",
                            "segment_id": "PGM_2",
                            "segment_key": "pgm_2"
                        }
                    ]
                }
            ]
        }
    ]
}

If anyone can help me with the code
I only have one keyboard, with 3 sections
- floor 1
- basement
- total

If anyone can help with the code, I would greatly appreciate it.

**Comment by SilvioMigu** [comment]
I have just this:
![image](https://user-images.githubusercontent.com/67691682/149676739-cb29cf95-57ca-47e3-8983-2c64e88cadac.jpeg)

**Comment by fdegier** [comment]
Hi, did you create a new account for the alarm? If so, then you need to login using that account to Jablonet to accept the terms. 

To get the ID you need to run the helper: https://github.com/fdegier/homebridge-jablotron-alarm#identify-jablotron-services-and-devices

Does this help?

**Comment by SilvioMigu** [comment]
No, I didn't create a new account.

Or do I need to close section and log back into jablotron account?

I don’t understand how i run the helper !?

I click on the link you left and it goes to the plugin's start page… sorry for my lack of understanding

**Comment by SilvioMigu** [comment]
ok, I already saw that you need to run “config-helper.js”.  
But where do I do it?

**Comment by fdegier** [comment]
Login to the shell of wherever you are running Homebridge, use that terminal.

**Comment by SilvioMigu** [comment]
![image](https://user-images.githubusercontent.com/67691682/149680189-d6efa035-f061-4e01-908f-4e98d4ca9882.png)

**Comment by SilvioMigu** [comment]
here ?  
Am I writing something wrong?  says error, cannot find module

**Comment by fdegier** [comment]
For Hoobs the locations are different:


HOOBS 2.1.1 - /usr/local/lib/node_modules/
HOOBS 3 - ~/.hoobs/node_modules/

**Comment by SilvioMigu** [comment]
As is Hoobs, I no longer need to run “config-helper.js” or do I have to go to 
/hoobs/node_modules/ and run ?  

I'm sorry, but these steps are already complicated for me, and you don't have to teach either...

**Comment by SilvioMigu** [comment]
![image](https://user-images.githubusercontent.com/67691682/149680960-a26c91ee-e2c2-4c47-8e90-4af0c56908fe.png)

**Comment by fdegier** [comment]
Yes you need to go to the module folder and run the config helper, as it will provide you with the configuration but more importantly the service ID, which there is no other way to retrieve it. 

If you want you can email me so we can setup a screen share meeting or you could create an account for me temporarily and I can run the command for you.

**Comment by SilvioMigu** [comment]
tomorrow I'll try to find out where the folder is.  if I can't, which is most likely I can't, we talk by email and you try to get into my pc with TeamViewer or another, to help me.  
thank you for everything, soon I will give news

**Comment by fdegier** [comment]
Did you manage to get it working?

**Comment by SilvioMigu** [comment]
I still couldn't find the module folder, to run the config helper.
I've already tried to find the raspberry pi's IP, to enter it, I'm not sure, if that's how I'll find the folder "~/.hoobs/node_modules/"

**Comment by fdegier** [comment]
Can you give me your email? I can setup a Zoom / Slack call to help you.

**Comment by SilvioMigu** [comment]
Yes, you will have to help me by zoom or another program.
But right now I'm working, I'm not at home.
I'm from Portugal 😉
We have to agree a time, compatible for both.

**Comment by fdegier** [comment]
Feel free to schedule: https://calendly.com/d/cqb-2jf-nm4/one-off-meeting

**Comment by SilvioMigu** [comment]
It's very nice of you to share a calendar to schedule help.
But I get home from work at 7pm, looks like it won't be easy.
You have no way of explaining or showing with a video, for example, how can I get to the jablotron module folder and run the run “config-helper.js”
It's an idea, if you find it easy to somehow explain it to me

**Comment by fdegier** [comment]
Ok I created an app that you can use to retrieve the config, all you need to do is enter your email and password. Check it out: 
https://jablotron-config-helper-api.herokuapp.com/docs

**Comment by SilvioMigu** [comment]
Thanks for everything, I'll see if this is what I can do!

**Comment by SilvioMigu** [comment]
Hi
I already tested the app, and finally found the ID
Then I copied the code that was created by the app, I don't know if I was supposed to copy all of it, but I copied it all and pasted it into the plugin.
But then I saw that the " "pincode": "Enter Your pincode" was missing in the code that the application created.
And so? Or do I have to put it on myself?
Thank you, the app is fantastic

**Comment by fdegier** [comment]
Great to hear! Yeah for pincode you just need to add the pincode you use on the keypad.

**Comment by SilvioMigu** [comment]
In the meantime I've been changing the jablotron password, and this morning the equipment from my MyJablobron app disappeared and also on the website, I can't find the equipment.
I've screwed up, for sure.
I don't know how it is with you, but as it was an autozied installer from Jablotron that installed everything, so he is the one who manages the problems. But I think I should have full access to the equipment, to be able to do something else.
I can only change the password and code, is this normal?

**Comment by fdegier** [comment]
That's annoying. I am a licensed installer so I have full access. In essence you can have it too, you need F-link and the master pincode, but do note that this software is quite tedious and if you have warranty on it from the installer, best to leave it.

Usually my clients only have a Jablotron account to login to the app. If people buy it and want to install it themself, they get F-link and therefor full root.

**Comment by SilvioMigu** [comment]
I copy this code, and past in plugin




{
    "status": "OK",
    "configs": [
        {
            "id": my i,
            "name": "Moradia Recarei",
            "username":"my email",
            "password": " my pass",
            "pincode": "my pincode",
            "service_type": "JA100",
            "autoRefresh": "True",
            "poolInterval": 60,
            "refreshOnStateChange": true,
            "debug": false,
            "sections": [
                {
                    "name": "Piso 1",
                    "segment_id": "STATE_1",
                    "segment_key": "section_1",
                    "armedMode": "Away"
                },
                {
                    "name": "Cave",
                    "segment_id": "STATE_2",
                    "segment_key": "section_2",
                    "armedMode": "Away"
                },
                {
                    "name": "Total",
                    "segment_id": "STATE_3",
                    "segment_key": "section_3",
                    "armedMode": "Away"
                }
            ],
            "switches": [
                {
                    "name": "Saída PG 1",
                    "segment_id": "PGM_1",
                    "segment_key": "pgm_1"
                },
                {
                    "name": "Saída PG 2",
                    "segment_id": "PGM_2",
                    "segment_key": "pgm_2"
                },
                {
                    "name": "Saída PG 3",
                    "segment_id": "PGM_3",
                    "segment_key": "pgm_3"
                },
                {
                    "name": "Saída PG 4",
                    "segment_id": "PGM_4",
                    "segment_key": "pgm_4"
                }
            ]
        }
    ],
    "platform": "Jablotron"
}

**Comment by SilvioMigu** [comment]
Now I'm waiting for the installer to put the device back into my jablotron account.
I do not know what happened.

Even after I copied the code created by the app, I logged in and out several times, waiting for it to appear for me to accept the terms, but it never appeared.

**Comment by SilvioMigu** [comment]
So do you think that when I tried to put Jablotron on the home app, for security reasons, the equipment was removed from my jablotron account?

**Comment by fdegier** [comment]
> So do you think that when I tried to put Jablotron on the home app, for security reasons, the equipment was removed from my jablotron account?

That would be impossible. I think you just have the wrong account. 

Your config in Homebridge needs to look something like this:

```
{
    "bridge": {
        "name": "redacted",
        "username": "redacted",
        "port": "redacted",
        "pin": "redacted",
        "bind": [
            "wlan0"
        ],
        "advertiser": "ciao"
    },
    "platforms": [
        {
            "name": "Jablotron",
            "services": [
                {
                    "id": "redacted",
                    "name": "Jablotron",
                    "username": "redacted",
                    "password": "redacted",
                    "pincode": "redacted",
                    "autoRefresh": true,
                    "poolInterval": 60,
                    "refreshOnStateChange": true,
                    "debug": false,
                    "sections": [
                        {
                            "name": "Alarm system",
                            "segment_id": "STATE_1",
                            "segment_key": "section_1",
                            "keyboard_key": "keyboard_2_3",
                            "armedMode": "Away"
                        },
                        {
                            "name": "Office",
                            "segment_id": "STATE_2",
                            "segment_key": "section_2",
                            "keyboard_key": "keyboard_2_3",
                            "armedMode": "Away",
                            "partiallyArmedMode": "Home"
                        },
                        {
                            "name": "PIR",
                            "segment_id": "STATE_3",
                            "segment_key": "section_3",
                            "keyboard_key": "keyboard_2_3",
                            "armedMode": "Away",
                            "partiallyArmedMode": "Home"
                        }
                    ],
                    "switches": [
                        {
                            "name": "Alarm switch",
                            "segment_id": "STATE_1",
                            "segment_key": "section_1"
                        }
                    ]
                }
            ],
            "platform": "Jablotron"
        },
        {
            "name": "Config",
            "port": 8090,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "en",
            "platform": "config"
        }
    ],
    "disabledPlugins": []
}
```

If you are uncomfortable editing JSON, I suggest you use the Homebridge settings menu.

**Comment by SilvioMigu** [comment]
I only have one account.
I don't even know how to create another one.
The installer took care of that.
Then I changed the password and the Pin.

Last night, I was changing my password, two or three times, and I was logging in and out a few times, to see if the part where I accepted the terms came up. But it didn't show up
However, the equipment disappeared.

**Comment by SilvioMigu** [comment]
When the installer puts the equipment on my account, I will test this code.
Thank you very much for your patience.

**Comment by fdegier** [comment]
To clarify: if you are already able to use the Jablotron app, you already accepted the terms. A lot of people were creating new accounts, then complaining it didn't work, because they never logged into that account before.

**Comment by SilvioMigu** [comment]
Its normal ?
In the homekit app it does not appear
I do not know what else to do...
![image](https://user-images.githubusercontent.com/67691682/154159370-0c40d41f-d19b-46d7-ae82-7e144fa597ae.png)

**Comment by SilvioMigu** [comment]
Now I created a bridge just for Jablotron
![image](https://user-images.githubusercontent.com/67691682/154161435-3d76c8e4-1ec6-4567-9715-120ef42224bf.png)

**Comment by SilvioMigu** [comment]
But when I go to add accessory, doesn't appear![image](https://user-images.githubusercontent.com/67691682/154161813-2e0b4b0a-1b7e-47bd-8e41-4173d234183d.png)

**Comment by fdegier** [comment]
What is the status now? Is your Jablotron app working again?

If it works in the Jablotron app, it should just work as well in Homebridge

**Comment by SilvioMigu** [comment]
Hi
In myjablotron application my owner email, the equipment does not appear.
However, I had my wife as a sub-owner and with her email I can access the myjablotron application.

However, I've already managed to get the plugin working in the homekit.
What is strange is that I got it with my owner email, which stopped working in the myjablotron app.

**Comment by SilvioMigu** [comment]
But it's already working
![image](https://user-images.githubusercontent.com/67691682/155984560-bd14ec78-f31d-47d0-aff0-6814d9008e19.jpeg)

**Comment by fdegier** [comment]
Ok, weird. Glad to hear that it works now, enjoy!

**Comment by SilvioMigu** [comment]
Hello again
Now I cannot arm or disarm the alarm.
After arming the alarm, then I can't disarm it, it only works again after I restart Hoobs.
In the logs this appears, do you know what it is?
![image](https://user-images.githubusercontent.com/67691682/157326382-271c12c1-41ae-4b3b-8a6b-a822027344c6.png)

**Comment by SilvioMigu** [comment]
I can now arm and disarm
in the hoobs log, it gives this error:
![image](https://user-images.githubusercontent.com/67691682/157328295-74a4f8e2-b87b-4e9f-a413-54d96e3e71ad.png)

**Comment by misncz** [comment]
I just noticed I'm getting "Unable to parse JSON" error too. Looks like it's properly communicating with the cloud and after some time I starts getting incorrect reply or gets broken by something unexpected. I'm investigating it now with some additional logging

**Comment by fdegier** [comment]
@misncz please see release https://github.com/fdegier/homebridge-jablotron-alarm/releases/tag/v2.5.0

**Comment by misncz** [comment]
> @misncz please see release https://github.com/fdegier/homebridge-jablotron-alarm/releases/tag/v2.5.0

@fdegier when I was debugging iPhone app traffic for thermometers I noticed they call API 1.9 but given thermometers worked fine with 1.6 I didn't change the API version in the client lib. Interesting ... good spot!

**Comment by fdegier** [comment]
> > @misncz please see release https://github.com/fdegier/homebridge-jablotron-alarm/releases/tag/v2.5.0
> 
> @fdegier when I was debugging iPhone app traffic for thermometers I noticed they call API 1.9 but given thermometers worked fine with 1.6 I didn't change the API version in the client lib. Interesting ... good spot!

Interesting, I tried 1.9 but it gave a bunch of errors so I suspected 1.9 was not available. We had a good run on 1.6, its been that version since the original release of this plugin.
