### ISSUE TITLE
Error: Bypass_dialog_timed

### ISSUE THREAD

**Issue by TarkDetrius** [fdegier/homebridge-jablotron-alarm#83]
Hello,

couple days ago I am getting an error when trying to do any change via the plugin. I am running a docker version of HB on DS920+. I expect it could have something to do with the change in the application where you need to wait or confirm that you want to proceed with the state change right away.

I am running the latest version 2.5.5

Expected Behavior

To set the arm modes

Steps To Reproduce

Click any arming button in HK

Logs

[4/15/2022, 8:13:50 AM] [Jablotron] Setting section state: section_1 => 1
[4/15/2022, 8:13:50 AM] [Jablotron] Switching section section_1 (using section_1) to new state: set
[4/15/2022, 8:13:53 AM] [Jablotron] {
  status: false,
  error_status: 'bypass_dialog_timed',
  checksum: '9f785d19e3d329edfb6ebff755a44f79',
  server_id: '9016932-1650003233',
  client_id: null
}
[4/15/2022, 8:13:53 AM] [Jablotron] Error: bypass_dialog_timed
    at /homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:36:31
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:68:21)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Configuration

{
    "name": "Jablotron",
    "services": [
        {
            "id": xxxx,
            "name": "Home",
            "username": "xxxxx",
            "password": "xxxx",
            "pincode": "xxxx",
            "autoRefresh": true,
            "poolInterval": 60,
            "refreshOnStateChange": true,
            "debug": false,
            "sections": [
                {
                    "name": "House",
                    "segment_id": "STATE_1",
                    "segment_key": "section_1",
                    "keyboard_key": "keyboard_2_3",
                    "armedMode": "Away",
                    "partiallyArmedMode": "Night"
                }
            ],
            "switches": [
                {
                    "name": "Dům",
                    "segment_id": "STATE_1",
                    "segment_key": "section_1"
                },
                {
                    "name": "Noční režim",
                    "segment_id": "STATE_2",
                    "segment_key": "section_2"
                },
                {
                    "name": "Pohyb",
                    "segment_id": "STATE_3",
                    "segment_key": "section_3"
                }
            ]
        }
    ],
    "platform": "Jablotron"
}
Environment

OS: DS 920+ docker file
Software: 2.5.5
Node:
npm:

**Comment by misncz** [comment]
We are not aware of any application changes. My installation can change statuses without issues incl complex scenes/automation
Have you agreed Jablotron cloud terms for account used by the plugin on MyJablotron website?

**Comment by TarkDetrius** [comment]
I did years ago :) nothing there (I would expect some pop up, correct?)

**Comment by fdegier** [comment]
Hi please see this issue: https://github.com/fdegier/homebridge-jablotron-alarm/issues/37

Bypass always means that you need to confirm it, I think that is something that should be handled on the users side.

**Comment by TarkDetrius** [comment]
Yeah you are right, the issue is caused by the prompt dialogue and there are ways around that. however it would be good if the plugin could still work with that (it is enough to wait 10s) and not cause errors.

Thank you for your great work!

**Comment by TarkDetrius** [comment]
that makes sense. however now the behaviour is that nothing gets flagged
and only after refresh the switch in HK is turned back to being off.
however feel free to close this issue :)

**Comment by fdegier** [comment]
No, you have a valid point, we should do something with this. I'm just not sure how to proceed

**Comment by cgajdzik** [comment]
Hi @fdegier , 
do you already have any solution in mind?

**Comment by fdegier** [comment]
@cgajdzik I've just gotten my sniffing setup in place again, I will setup a scenario to test it and see if we can bypass it.

**Comment by fdegier** [comment]
So I was finally able to test this, and the good thing is, its an easy fix 😄 will tag you in the PR.

**Comment by fdegier** [comment]
A new update, I tried adding it to api 1.8 but it does not work, I can only make it work in 1.9 which on itself is a massive upgrade. I started preparing for the upgrade to 1.9 but it will take a while.

**Comment by fdegier** [comment]
Support added in 3.0.0
