### ISSUE TITLE
Support for API version 1.9

### ISSUE THREAD

**Issue by fdegier** [fdegier/homebridge-jablotron-alarm#84]
A new API version was released by Jablotron, its a breaking change with a lot of changes to data structures and endpoints. I have started to work on this in https://github.com/fdegier/JablotronPy but still need to explore and document a lot of end points. 

CC: @misncz @grzegorz914

**Comment by Martasdx** [comment]
How does it look like? Happy to help if I am able to

**Comment by fdegier** [comment]
Do you mean the actual endpoint and their behavior? I have documented a few but haven't had the time to document the rest.
