### ISSUE TITLE
Update installation guide in the README

### ISSUE THREAD

**Issue by spookercz** [fdegier/homebridge-jablotron-alarm#88]
In the section of "Identify Jablotron services and devices" you are guiding to run this command:

cd **/usr/local/lib/node_modules/homebridge-jablotron**
node config-helper.js username password

But my homebridge-jablotron is stored elswhere:

Node.js Version: v18.13.0
Node.js Path: /opt/homebridge/bin/node
Plugin Path: **/var/lib/homebridge/node_modules/homebridge-jablotron**

* **Homebridge-jablotron plugin version:** homebridge-jablotron v2.5.6
* **Operating System and OS Version:** Raspbian

**Comment by fdegier** [comment]
Thanks for your issue! What do you propose I should do? There are many ways to install Homebridge and plugins, mine is just an example.

**Comment by spookercz** [comment]
Up to you, I am a newbie to this, so I was looking for straightforward
manual. My installation was using the home-bridge raspberry pi default
image, so this was the default path. Maybe mention this path as an
alternative where to find the right folder with the file. Anyway, thanks
for your plugin, really appreciated.

BR Michal

st 18. 1. 2023 v 17:02 odesílatel Fred de Gier ***@***.***>
napsal:

**Comment by misncz** [comment]
@spookercz I have the manual change on my todo list since I was reinstalling using raspbian too. Glad you figured out where the plugin location sits with raspbian!

**Comment by fdegier** [comment]
Thanks for the feedback both. I actually prefer Docker and have been running HomeBridge in Docker for years now. I should probably make that the default in the README as its 10x simpler than the current implementation.
