### ISSUE TITLE
Jablotron error: getaddrinfo ENOTFOUND api.jablonet.net

### ISSUE THREAD

**Issue by BEskandari** [fdegier/homebridge-jablotron-alarm#94]
**Describe The Problem:**
Getting the below message every few hours

**To Reproduce:**
N/A

**Logs:**

```
[04/04/2023, 10:32:51] [Jablotron] Error: getaddrinfo ENOTFOUND api.jablonet.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.jablonet.net'
}
```

**Environment:**

* **Homebridge Version:** 1.6.0
* **Node Version:** 18.15.0
* **Homebridge-jablotron plugin version:** 2.6.0
* **Operating System and OS Version:** Raspbian

**Comment by fdegier** [comment]
Thanks for reporting, this has been reported a few times. I'll add more debug to see what the cause is. I've never seen this error personally.
